Repository team-echoist/web-frontend, pull requests merged in 2024-06, with the labels that each got.

#24 관리자 회원가입 api연동
  admin-refact/src/api/AxiosInstance.js
  admin-refact/src/layouts/authentication/sign-in/index.jsx
  admin-refact/src/layouts/authentication/sign-up/index.jsx
  admin-refact/src/layouts/dashboard/detail/index.jsx
  web/src/app/page.tsx
Labels: Domian: Front, Status: In Progress, Type: Enhancement

#20 어드민 로그인 구현
  admin-refact/src/api/AxiosInstance.js
  admin-refact/src/layouts/authentication/sign-in/index.jsx
Labels: Domian: Front, Type: Enhancement

#30 Feat/fixbug 로그인 로직 cookie로 변경& axiosinstance cookie값 가져오는 로직으로 변경& 로그아웃 로직 구현& 토큰 여부에 따른 리다이렉션 처리 완료
  admin-refact/package-lock.json
  admin-refact/package.json
  admin-refact/src/App.jsx
  admin-refact/src/api/AxiosInstance.js
  admin-refact/src/examples/Navbars/DefaultNavbar/DefaultNavbarMobile.jsx
  admin-refact/src/examples/Navbars/DefaultNavbar/index.jsx
  admin-refact/src/examples/Sidenav/index.jsx
  admin-refact/src/layouts/authentication/sign-in/index.jsx
  admin-refact/src/layouts/authentication/sign-up/index.jsx
  admin-refact/src/layouts/dashboard/api/fetchDetailData.js
  admin-refact/src/layouts/dashboard/data/detailChartData.js
  admin-refact/src/layouts/dashboard/detail/index.jsx
  admin-refact/src/layouts/dashboard/index.jsx
  admin-refact/src/layouts/profile/api/index.js
  admin-refact/src/layouts/profile/index.jsx
  admin-refact/src/routes.jsx
  admin-refact/src/utils/handleLogout.js
Labels: Domian: Front, Status: Done, Type: Bug

#35 Feat/bug 전반적인 버그 수정작업및 불필요한 코드 삭제
  admin/index.html
  admin/public/linkedout.webp
  admin/src/App.jsx
  admin/src/assets/theme/index.jsx
  admin/src/examples/Breadcrumbs/index.jsx
  admin/src/examples/Footer/index.jsx
  admin/src/examples/Navbars/DashboardNavbar/index.jsx
  admin/src/layouts/authentication/components/CoverLayout/index.jsx
  admin/src/layouts/authentication/components/Footer/index.jsx
  admin/src/layouts/authentication/sign-in/index.jsx
  admin/src/layouts/authentication/sign-up/index.jsx
  admin/src/layouts/dashboard/index.jsx
  package-lock.json
Labels: Domian: Front, Priority: High, Status: Done

#40 Feat/fixbug 대시보드 today essay 버그 수정
  admin/src/layouts/dashboard/detail/index.jsx
  admin/vercel.json
  admin/vite.config.js
Labels: Domian: Front, Priority: High, Type: Bug

#45 Feat/notice 공지사항 ui세팅 및 api 연동
  admin/package-lock.json
  admin/package.json
  admin/src/api/index.js
  admin/src/components/BackgroundCard/content/DefaultContent.jsx
  admin/src/components/BackgroundCard/content/TwoContent.jsx
  admin/src/components/BackgroundCard/index.jsx
  admin/src/components/MDButton/index.jsx
  admin/src/components/Tables/data/authorsTableData.jsx
  admin/src/components/Tables/data/projectsTableData.jsx
  admin/src/components/Tables/index.jsx
  admin/src/examples/Tables/DataTable/DataTableBodyCell.jsx
  admin/src/examples/Tables/DataTable/index.jsx
  admin/src/layouts/notice/detail/index.jsx
  admin/src/layouts/notice/index.jsx
  admin/src/layouts/profile/components/Header/index.jsx
  admin/src/layouts/profile/components/PlatformSettings/index.jsx
  admin/src/layouts/profile/index.jsx
  admin/src/layouts/tables/data/authorsTableData.jsx
  admin/src/layouts/tables/index.jsx
  admin/src/layouts/update/index.jsx
  admin/src/routes.jsx
Labels: Domian: Front, Priority: Urgent

#47 Feat/inquire 문의페이지 ui 및 api 연동
  admin/src/api/index.js
  admin/src/components/BackgroundCard/content/TwoContent.jsx
  admin/src/components/Tables/data/inquireTableData.jsx
  admin/src/components/Tables/data/noticeTableData.jsx
  admin/src/components/Tables/data/projectsTableData.jsx
  admin/src/examples/Tables/DataTable/index.jsx
  admin/src/layouts/inquire/index.jsx
  admin/src/layouts/notice/detail/index.jsx
  admin/src/layouts/notice/index.jsx
  admin/src/layouts/profile/index.jsx
  admin/src/layouts/update/index.jsx
  admin/src/routes.jsx
Labels: Domian: Front
