Repository team-echoist/web-frontend, pull requests merged in 2024-07, with the labels that each got.

#58 Feat/tables essay 상세페이지 기능 구현
  admin/.env
  admin/src/components/Tables/data/essayTableData.jsx
  admin/src/components/Tables/data/reportListTableData.jsx
  admin/src/components/Tables/data/reportTableData.jsx
  admin/src/components/Tables/data/userTableData.jsx
  admin/src/layouts/essay/components/EditModal/index.jsx
  admin/src/layouts/essay/detail/index.jsx
  admin/src/layouts/reports/components/EditModal/index.jsx
  admin/src/layouts/reports/detail/index.jsx
  admin/src/layouts/reports/index.jsx
  admin/src/layouts/users/components/EditModal/index.jsx
  admin/src/layouts/users/detail/index.jsx
  admin/src/layouts/users/index.jsx
  admin/src/routes.jsx
Labels: Domian: Front, Type: Enhancement

#59 report 상세 페이지 기능 및 디자인 적용
  admin/src/layouts/reports/detail/index.jsx
Labels: Domian: Front, Status: In Progress, Type: Enhancement

#63 Feat/tables reports api 요청 방법 변경, user 디자인 수정
  admin/.env
  admin/package-lock.json
  admin/package.json
  admin/src/layouts/profile/index.jsx
  admin/src/layouts/reports/components/EditModal/index.jsx
  admin/src/layouts/reports/detail/index.jsx
  admin/src/layouts/users/components/EditModal/index.jsx
  admin/src/layouts/users/detail/index.jsx
  admin/src/layouts/users/index.jsx
Labels: Domian: Front, Status: In Progress

#65 Feat/form : user 정보수정 모달 렌더링 시 기존 유저 정보 출력 및 디자인 수정
  admin/package-lock.json
  admin/src/layouts/essay/components/EditModal/index.jsx
  admin/src/layouts/essay/detail/index.jsx
  admin/src/layouts/users/components/EditModal/index.jsx
  admin/src/layouts/users/detail/index.jsx
Labels: Domian: Front

#74 Feat/onboarding 온보딩 소스 중간 merge
  web/next.config.js
  web/package-lock.json
  web/package.json
  web/public/sw.js.map
  web/src/pages-flat/onboarding/ui/ImageRenderer.tsx
  web/src/pages-flat/onboarding/ui/firststepcontent.tsx
  web/src/pages-flat/onboarding/ui/generalcontent.tsx
  web/src/pages-flat/onboarding/ui/onboarding.tsx
  web/src/pages-flat/onboarding/ui/onboardingLayout.tsx
  web/src/shared/assets/img/onboarding_final_1.gif
  web/src/shared/assets/img/onboarding_final_2.gif
  web/src/shared/assets/img/onboarding_final_3.gif
  web/src/shared/assets/img/onboarding_final_4.gif
  web/src/shared/assets/img/splash_final_clear.gif
  web/src/shared/assets/video/apponboarding_1.webm
  web/src/shared/assets/video/apponboarding_2.webm
  web/src/shared/assets/video/apponboarding_3.webm
  web/src/shared/assets/video/apponboarding_4.webm
  web/src/shared/assets/video/apponboarding_5.webm
  web/src/shared/lib/style/index.ts
  web/src/shared/lib/style/updateBtnStyle.ts
  web/src/shared/styles/color.ts
  web/src/shared/types/btnType.ts
  web/src/shared/ui/button/button.styled.ts
  web/src/shared/ui/button/button.tsx
Labels: Domian: Front, Priority: Medium

#79 Feat/onboarding 온보딩 스와이퍼 구현및 폰트 전역설정
  admin/package-lock.json
  web/.gitignore
  web/next.config.js
  web/package-lock.json
  web/package.json
  web/public/sw.js.map
  web/src/app/GlobalStyle.ts
  web/src/app/fonts/PretendardWoff/Pretendard-Black.woff
  web/src/app/fonts/PretendardWoff/Pretendard-Bold.woff
  web/src/app/fonts/PretendardWoff/Pretendard-ExtraBold.woff
  web/src/app/fonts/PretendardWoff/Pretendard-ExtraLight.woff
  web/src/app/fonts/PretendardWoff/Pretendard-Light.woff
  web/src/app/fonts/PretendardWoff/Pretendard-Medium.woff
  web/src/app/fonts/PretendardWoff/Pretendard-Regular.woff
  web/src/app/fonts/PretendardWoff/Pretendard-SemiBold.woff
  web/src/app/fonts/PretendardWoff/Pretendard-Thin.woff
  web/src/app/fonts/PretendardWoff2/Pretendard-Black.woff2
  web/src/app/fonts/PretendardWoff2/Pretendard-Bold.woff2
  web/src/app/fonts/PretendardWoff2/Pretendard-ExtraBold.woff2
  web/src/app/fonts/PretendardWoff2/Pretendard-ExtraLight.woff2
  web/src/app/fonts/PretendardWoff2/Pretendard-Light.woff2
  web/src/app/fonts/PretendardWoff2/Pretendard-Medium.woff2
  web/src/app/fonts/PretendardWoff2/Pretendard-Regular.woff2
  web/src/app/fonts/PretendardWoff2/Pretendard-SemiBold.woff2
  web/src/app/fonts/PretendardWoff2/Pretendard-Thin.woff2
  web/src/app/homeClient.tsx
  web/src/app/layout.tsx
  web/src/app/page.tsx
  web/src/app/registry.tsx
  web/src/pages-flat/onboarding/ui/content/firstStepContent.tsx
  web/src/pages-flat/onboarding/ui/content/general/generalContent.tsx
  web/src/pages-flat/onboarding/ui/content/general/imageRenderer.tsx
  web/src/pages-flat/onboarding/ui/content/general/textRenderer.tsx
  web/src/pages-flat/onboarding/ui/generalcontent.tsx
  web/src/pages-flat/onboarding/ui/layout/onboardingLayout.tsx
  web/src/pages-flat/onboarding/ui/onboarding.tsx
  web/src/pages-flat/onboarding/ui/onboardingLayout.tsx
  web/src/shared/assets/fonts/index.ts
  web/src/shared/assets/img/IndicatorBarStep1.svg
  web/src/shared/assets/img/IndicatorBarStep2.svg
  web/src/shared/assets/img/IndicatorBarStep3.svg
  web/src/shared/assets/img/IndicatorBarStep4.svg
  web/src/shared/assets/img/onboarding_final_1.gif
  web/src/shared/assets/img/onboarding_final_2.gif
  web/src/shared/assets/img/onboarding_final_3.gif
  web/src/shared/assets/img/onboarding_final_4.gif
  web/src/shared/lib/style/index.ts
  web/src/shared/lib/style/updateBtnStyle.ts
  web/src/shared/lib/swiper/swiper.tsx
  web/src/shared/styles/GlobalStyles.ts
  web/src/shared/styles/device.ts
  web/src/shared/styles/index.ts
  web/src/shared/types/index.ts
  web/src/shared/ui/button/button.styled.ts
  web/src/shared/ui/button/button.tsx
  web/src/shared/ui/indicator/index.ts
  web/src/shared/ui/indicator/indicatorBar.tsx
Labels: Domian: Front
